### PR TITLE
Fix a bug in the port selection for the nested Jupyter servers.

### LINKED ISSUE #884: Datalab is loading on different (incorrect) user workspace
Datalab is randomly loading under different users workspace within the serving VM for the datalab app engine (datalab_main).

I am attaching an image of datalab for which I list the workspace folder and you can see that it is on the workspace of my colleague.

We suspect this has been happening for a while since we have randomly disappearing files from workspaces. We also realize that these VMs have some background linux process to synchronize source code with git so perhaps that is the cause also of the missing files.

In any case, this is an issue and it is affecting our work now.
screen shot 2016-06-27 at 11 18 08 am

### PR DESCRIPTION
**Pull request by ojarjur**
Previously, Datalab was picking the next port that it wanted Jupyter
to run on, passing that to the launched Jupyter process using the
'--port' flag, and then assuming that the server did in fact start
listening on that port.

However, if the port selected was already in use, then Jupyter would
automatically try the next port in sequence. That could cause an issue
where the one Jupyter server (for one user) was listening on a port
that we thought was being used by the Jupyter server for a different
user.

This change fixes that bug by doing the following:

1. Verifying that the next port is free before we try to start a
   Jupyter server listening on it.
2. Telling the Jupyter server to not try any additional ports if
   the one specified was not available (so it will instead die in
   that situation).

The combination of these two steps effectively moves the retry
logic for picking a port out of the Jupyter process and in to the
wrapping Node server.

There are still two failure cases that can manifest even with this
change.

The first is that if the attempt to start a Jupyter server
fails more than 10 times, then the retry logic will give up and
an internal error will be reported to the user. This failure mode
always existed, but now we will be properly tracking it.

The second is a race condition where another process grabs the
requested port between the time when we verify that it is free
and the time that the launched Jupyter server starts up. If that
happens, then the Jupyter server will kill itself, and it will
be removed from the users->Jupyter servers map. However, the
request that caused us to spin up a Jupyter server to begin
with will be forwarded to the process that took hold of the
assigned port.

This failure case should be difficult enough to trigger that it
will not occur in practice.

We believe this will fix the issue reported in #884

### CODE REVIEW

File: sources/web/datalab/jupyter.ts [hunk 1]
```diff
@@ -137,7 +137,16 @@ function createJupyterServer(userId: string, resolved: (server: JupyterServer)=>
         server.proxy.on('proxyRes', responseHandler);
         server.proxy.on('error', errorHandler);
 
-        resolved(server);
+        tcp.waitUntilUsed(server.port).then(
```
Comment (qimingj) [inline sources/web/datalab/jupyter.ts]: Maybe set a larger timeout value? Default is only 300ms and not sure Jupyter is quick enough to start up especially in a potentially heavy loaded VM.

Comment (ojarjur) [inline sources/web/datalab/jupyter.ts]: Done.

**Comment by qimingj** [comment]
LGTM.
